<a href="https://colab.research.google.com/github/LeyvinoBezerra/API-de-Consulta/blob/main/Aula_2_1_Numpy_para_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Documentação Numpy
https://numpy.org/doc/stable/reference/index.html

https://numpy.org/doc/stable/reference/generated/numpy.ndarray.size.html

In [ ]:
#importação da biblioteca
import numpy as np

###Preenchimento de Arrays com números específicos

In [ ]:
#Array de uma dimensão
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
one_dimensional_array
#print(one_dimensional_array)

array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])

In [ ]:
#Array de duas dimensões
two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


In [ ]:
# Preencher Array com zeros e uns
array_zeros = np.zeros(5)
print(array_zeros)
array_uns = np.ones([2,4])
print(array_uns)

[0. 0. 0. 0. 0.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#Preencher Array com uma sequencia de numeros [lim_inferior, lim_superior)
#O intervalo é fechado no limite inferior e aberto no limite superior
sequence_of_integers = np.arange(5, 12)
print(sequence_of_integers)

[ 5  6  7  8  9 10 11]


In [ ]:
#preencher Array com números inteiros aleatórios
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6))
print(random_integers_between_50_and_100)

[93 75 99 64 84 51]


In [ ]:
#preencher Array com números float aleatórios
random_floats_between_0_and_1 = np.random.random([6])
print(random_floats_between_0_and_1)

[0.83052217 0.87269093 0.13747705 0.81447274 0.65108342 0.56032304]


###Operações Matemáticas com Numpy

In [ ]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

[2.83052217 2.87269093 2.13747705 2.81447274 2.65108342 2.56032304]


In [ ]:
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300)

[279 225 297 192 252 153]


#Tarefa: Criar um dataset linear


*   Criar um array "Feature" com uma sequencia de inteiros de 6 a 20 (inclusive)
*   Criar um array "Label" onde:
   
   Label = (3)(feature) + 4


In [ ]:
#@title clique para ver a resposta

Feature = np.arange(6,21)
print(Feature)
Label = (Feature*3)+4
print(Label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]




1.   Adicione algum ruído ao dataset

Para que o dataset pareça mais real, insira um ruído aleatório a cada elemento do array Label. Adicione um um valor ponto-flutuante aleatório entre -2 e 2.
random.random()*(b-a)+a





In [ ]:
#@title Clique para ver a resposta

noise = (np.random.random([15]) * 4) - 2
print(noise)
Label = Label + noise
print(Label)

[ 1.37650913 -0.34202216  1.47008153  0.10185457  1.02286747  0.79464222
  0.35062621  1.77292886 -0.25999881 -1.00979259 -1.48891668 -0.32462806
 -1.83559515 -1.94855984 -0.78116033]
[23.37650913 24.65797784 29.47008153 31.10185457 35.02286747 37.79464222
 40.35062621 44.77292886 45.74000119 47.99020741 50.51108332 54.67537194
 56.16440485 59.05144016 63.21883967]


In [ ]:
Label.size

15